"""Who holds a durable run's credentials: the owner, or the harness (TASK-40).

Every live stage against a persistent Controller instance needs credentials:
the instance's ``local-rescue`` console password, the domain Administrator's,
each staged account's, the daily administrator's first-logon change and the
kept workstation's break-glass passwords.  For the keeper those stay the
OWNER's: typed at the controlling terminal, held in memory, never stored.
For a THROWAWAY rehearsal the owner decided on 2026-09-30 that the harness
holds its own and runs every stage unattended.  This module is that choice:

* **Custody is a property of the instance, fixed at creation.**  The instance
  marker carries ``credential_custody`` (``owner`` or ``agent``; absent means
  ``owner``) and ``throwaway``.  ``agent`` requires ``throwaway: true``, and
  both are written only by ``persistent-up`` when it creates the instance
  (``CUSTODY=agent THROWAWAY=1``).  Nothing changes either later.  A kept
  workstation inherits its bound instance's custody.
* **The store.**  An agent-custody instance keeps its generated credentials
  in ``<instance>/custody/credentials.json`` (directory 0700, file 0600,
  atomic replacement, the replaced copy shredded); a kept workstation bound
  to one keeps its break-glass passwords in ``<workstation>/custody/``.  An
  owner-custody instance never has one, and a store beside one is refused.
  ``destroy`` shreds a store before anything else.  Values never reach argv,
  the environment, the marker, the evidence, a transcript or stdout/stderr;
  every retained-evidence scan of an agent-custody run adds the whole store
  to its needles (``AgentCredentialSource.scan_values``).
* **One interface.**  ``credential_source`` reads the marker and returns an
  ``OwnerCredentialSource`` (today's prompts, byte-identical: it calls the
  runner's own prompt function with the runner's own text) or an
  ``AgentCredentialSource`` (the store).

The security trade-off, stated plainly: a throwaway instance's credentials sit
in a 0600 file in an ignored directory for the instance's whole life, like the
one-use ``publication.iso`` a kept workstation holds, and are shredded on
destroy.  That is acceptable for a rehearsal directory that is destroyed after
use and never for the keeper, which stays owner custody.

Standard library only, and importable in both of ``simulation_overlay``'s run
modes: it is the marker's validator as well as the runners' source.
"""

from __future__ import annotations

import contextlib
import fcntl
import json
import os
import secrets
import stat
import string
from datetime import UTC, datetime
from pathlib import Path
from typing import Callable, Iterable, Mapping

#: Marker keys (instance marker) and their values.
CUSTODY_KEY = "credential_custody"
THROWAWAY_KEY = "throwaway"
OWNER = "owner"
AGENT = "agent"
CUSTODIES = (OWNER, AGENT)

#: The store's names, inside an instance's or a kept workstation's state.
CUSTODY_DIR_NAME = "custody"
STORE_NAME = "credentials.json"
#: Fixed names, never random ones: an interrupted rewrite leaves one
#: predictable leftover that the next rewrite truncates (or shreds) and
#: ``shred`` knows about.
STORE_STAGING_NAME = "." + STORE_NAME + ".new"
STORE_RETIRED_NAME = "." + STORE_NAME + ".old"
STORE_NAMES = frozenset({STORE_NAME, STORE_STAGING_NAME, STORE_RETIRED_NAME})
STORE_SCHEMA = 1
STORE_KIND = "telos-credential-custody"
SCOPE_INSTANCE = "instance"
SCOPE_WORKSTATION = "workstation"

#: Account record fields (instance scope, by CONTRACT ROLE, never a name).
ACCOUNT_FIELDS = frozenset({
    "temporary", "current", "pending", "pending_kind", "pending_must_change",
    "pending_not_live_utc"})
ACCOUNT_SECRET_FIELDS = ("temporary", "current", "pending")
PENDING_FIRST_LOGON = "first-logon"
PENDING_RESET = "reset"
#: Break-glass slots (workstation scope).
ARCH_LOCAL_RESCUE = "arch_local_rescue"
WINDOWS_LOCAL_ADMINISTRATOR = "windows_local_administrator"
BREAK_GLASS_SLOTS = (ARCH_LOCAL_RESCUE, WINDOWS_LOCAL_ADMINISTRATOR)
BREAK_GLASS_FIELDS = frozenset({"current", "pending"})

#: Generated values: letters and digits only, at least one of each of upper
#: case, lower case and digit.  Three character classes satisfy Samba's
#: default complexity; no punctuation keeps every value typeable by gate 6's
#: US-layout QMP keyboard and independent of the guest's input locale -- the
#: same reasoning as gate 6's own generated local credential.  The runner's
#: own checks (the directory policy against the account name, typeability)
#: still judge every candidate before it is used.
GENERATED_LENGTH = 24
ALPHABET = string.ascii_uppercase + string.ascii_lowercase + string.digits
GENERATION_ATTEMPTS = 64

NOTE = (
    "agent credential custody (owner decision 2026-09-30): generated by the "
    "harness for a THROWAWAY instance and kept here for its whole life; "
    "shredded by destroy. Never copy a value out of this file")


class CustodyError(RuntimeError):
    """Custody refused, or a store is unusable.  Messages carry no value."""


def _now() -> str:
    return datetime.now(UTC).isoformat()


# -- the marker ------------------------------------------------------------
def marker_custody(marker: Mapping) -> str:
    """The marker's custody; absent means the owner's, as it always was."""
    value = marker.get(CUSTODY_KEY, OWNER)
    if value not in CUSTODIES:
        raise CustodyError(
            f"the marker's {CUSTODY_KEY} must be one of "
            + ", ".join(CUSTODIES))
    return value


def marker_throwaway(marker: Mapping) -> bool:
    value = marker.get(THROWAWAY_KEY, False)
    if not isinstance(value, bool):
        raise CustodyError(f"the marker's {THROWAWAY_KEY} is not true or false")
    return value


def validate_marker(marker: Mapping) -> None:
    """Refuse an unknown custody, and agent custody on a kept instance."""
    custody = marker_custody(marker)
    throwaway = marker_throwaway(marker)
    if custody == AGENT and not throwaway:
        raise CustodyError(
            "agent credential custody is only for a throwaway instance: the "
            "marker records agent custody without throwaway true")


def creation_fields(custody: str, throwaway: bool) -> dict:
    """The marker fields ``create`` records; refuses what may never exist."""
    fields = {CUSTODY_KEY: custody, THROWAWAY_KEY: bool(throwaway)}
    validate_marker(fields)
    return fields


def requested_custody(custody: str | None, throwaway: bool) -> tuple[str, bool]:
    """``CUSTODY``/``THROWAWAY`` as asked for at creation, or a refusal."""
    chosen = OWNER if custody in (None, "") else custody
    if chosen not in CUSTODIES:
        raise CustodyError("CUSTODY must be owner or agent")
    if chosen == AGENT and not throwaway:
        raise CustodyError(
            "CUSTODY=agent requires THROWAWAY=1: the harness holds its own "
            "credentials only for a throwaway rehearsal instance; the keeper "
            "stays owner custody")
    return chosen, bool(throwaway)


# -- generated values -------------------------------------------------------
def generate_password(
    *, checks: Iterable[Callable[[str], str | None]] = (),
    avoid: Iterable[str | bytes] = (), length: int = GENERATED_LENGTH,
) -> str:
    """One new credential from ``secrets``, judged by every *check*.

    Each check returns ``None`` for an acceptable value and a reason (which
    never quotes it) otherwise; a value equal to anything in *avoid* is
    drawn again.  The bound is generous: a candidate fails a check only by
    containing an account name, which a 24-character draw almost never does.
    """
    if length < 3:
        raise CustodyError("a generated credential needs at least 3 characters")
    checks = tuple(checks)
    avoided = {value.decode("utf-8", "replace") if isinstance(value, bytes)
               else value for value in avoid if value}
    draw = secrets.SystemRandom()
    for _attempt in range(GENERATION_ATTEMPTS):
        characters = [
            draw.choice(string.ascii_uppercase),
            draw.choice(string.ascii_lowercase),
            draw.choice(string.digits),
        ] + [draw.choice(ALPHABET) for _ in range(length - 3)]
        draw.shuffle(characters)
        value = "".join(characters)
        if value in avoided:
            continue
        if any(check(value) is not None for check in checks):
            continue
        return value
    raise CustodyError(
        "no generated credential satisfied the policy; nothing was stored")


# -- the store ----------------------------------------------------------------
def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def shred_file(path: Path) -> None:
    """Overwrite a regular file with random bytes, fsync, unlink.

    Best effort by nature, like ``workstation_instance``'s shred of the
    publication: a copy-on-write filesystem or an SSD's remapping can keep
    old blocks.  It still guarantees no other name of the inode keeps
    readable content.
    """
    descriptor = os.open(path, os.O_WRONLY | os.O_NOFOLLOW)
    try:
        info = os.fstat(descriptor)
        if not stat.S_ISREG(info.st_mode):
            raise CustodyError(f"refusing to shred a non-regular file: {path}")
        remaining = info.st_size
        while remaining:
            chunk = secrets.token_bytes(min(remaining, 64 * 1024))
            remaining -= os.write(descriptor, chunk)
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    os.unlink(path)


def _string_or_none(value: object) -> bool:
    return value is None or (isinstance(value, str) and bool(value))


class CustodyStore:
    """One custody directory: a single private JSON document of credentials."""

    def __init__(self, state: Path, *, scope: str, name: str) -> None:
        if scope not in (SCOPE_INSTANCE, SCOPE_WORKSTATION):
            raise CustodyError(f"unknown custody scope {scope!r}")
        self.state = Path(state).absolute()
        self.scope = scope
        self.name = name
        self.directory = self.state / CUSTODY_DIR_NAME
        self.path = self.directory / STORE_NAME

    def __repr__(self) -> str:
        return f"CustodyStore({self.scope}={self.name!r})"

    # -- presence and permissions ------------------------------------------
    def exists(self) -> bool:
        return os.path.lexists(self.directory)

    def _check_directory(self) -> None:
        try:
            info = os.lstat(self.directory)
        except FileNotFoundError as error:
            raise CustodyError(
                f"the {self.scope} {self.name} has no custody store at "
                f"{self.directory}") from error
        if not stat.S_ISDIR(info.st_mode):
            raise CustodyError(
                f"the custody store is not a real directory: {self.directory}")
        if info.st_uid != os.geteuid() or info.st_mode & 0o077:
            raise CustodyError(
                f"the custody store must be owned by this user and mode 0700: "
                f"{self.directory}")

    @contextlib.contextmanager
    def _locked(self):
        """An exclusive lock on the store directory for one read-modify-write."""
        self._check_directory()
        descriptor = os.open(self.directory, os.O_RDONLY | os.O_DIRECTORY)
        try:
            fcntl.flock(descriptor, fcntl.LOCK_EX)
            yield
        finally:
            with contextlib.suppress(OSError):
                fcntl.flock(descriptor, fcntl.LOCK_UN)
            os.close(descriptor)

    # -- the document -------------------------------------------------------
    def _validated(self, raw: object) -> dict:
        if not isinstance(raw, dict):
            raise CustodyError(f"the custody store is not an object: {self.path}")
        if (raw.get("schema") != STORE_SCHEMA or raw.get("kind") != STORE_KIND
                or raw.get("scope") != self.scope
                or raw.get("name") != self.name):
            raise CustodyError(
                f"the custody store does not belong to the {self.scope} "
                f"{self.name}: {self.path}")
        if self.scope == SCOPE_INSTANCE:
            if not isinstance(raw.get("console"), str) or not raw["console"]:
                raise CustodyError(
                    "the instance custody store holds no console credential")
            if not _string_or_none(raw.get("administrator")):
                raise CustodyError(
                    "the custody store's administrator entry is malformed")
            accounts = raw.get("accounts", {})
            if not isinstance(accounts, dict):
                raise CustodyError("the custody store's accounts are malformed")
            for role, entry in accounts.items():
                if not isinstance(role, str) or not isinstance(entry, dict):
                    raise CustodyError(
                        "the custody store has a malformed account entry")
                if set(entry) - ACCOUNT_FIELDS:
                    raise CustodyError(
                        "a custody account entry carries an unexpected field")
                if not all(_string_or_none(entry.get(key))
                           for key in ACCOUNT_SECRET_FIELDS):
                    raise CustodyError(
                        "a custody account entry has a malformed value")
                if entry.get("pending_kind") not in (
                        None, PENDING_FIRST_LOGON, PENDING_RESET):
                    raise CustodyError(
                        "a custody account entry has an unknown pending kind")
        else:
            glass = raw.get("break_glass", {})
            if not isinstance(glass, dict) or set(glass) - set(
                    BREAK_GLASS_SLOTS):
                raise CustodyError(
                    "the workstation custody store's break-glass slots are "
                    "malformed")
            for entry in glass.values():
                if (not isinstance(entry, dict)
                        or set(entry) - BREAK_GLASS_FIELDS
                        or not all(_string_or_none(entry.get(key))
                                   for key in BREAK_GLASS_FIELDS)):
                    raise CustodyError(
                        "a break-glass custody entry is malformed")
        return raw

    def read(self) -> dict:
        """The validated document, or a refusal naming the store only."""
        self._check_directory()
        try:
            descriptor = os.open(self.path, os.O_RDONLY | os.O_NOFOLLOW)
        except OSError as error:
            raise CustodyError(
                f"the custody store cannot be opened: {self.path}") from error
        try:
            info = os.fstat(descriptor)
            if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.geteuid()
                    or info.st_mode & 0o077):
                raise CustodyError(
                    f"the custody store must be a regular file owned by this "
                    f"user, mode 0600: {self.path}")
            with os.fdopen(descriptor, "r", encoding="utf-8") as stream:
                descriptor = -1
                raw = json.load(stream)
        except (OSError, ValueError) as error:
            raise CustodyError(
                f"the custody store is unreadable: {self.path}") from error
        finally:
            if descriptor >= 0:
                os.close(descriptor)
        return self._validated(raw)

    def _write(self, document: dict) -> None:
        """Stage, fsync, keep the old copy by a second name, rename, shred it.

        The store's name always holds a whole document (old or new); the old
        inode is shredded after the rename rather than left to the free list.
        """
        document = self._validated(document)
        staging = self.directory / STORE_STAGING_NAME
        retired = self.directory / STORE_RETIRED_NAME
        descriptor = os.open(
            staging, os.O_WRONLY | os.O_CREAT | os.O_TRUNC | os.O_NOFOLLOW,
            0o600)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
                stream.write(json.dumps(document, indent=2, sort_keys=True)
                             + "\n")
                stream.flush()
                os.fsync(stream.fileno())
            os.chmod(staging, 0o600)
            self._discard_retired()
            if os.path.lexists(self.path):
                os.link(self.path, retired)
            os.replace(staging, self.path)
            _fsync_directory(self.directory)
        except BaseException:
            with contextlib.suppress(OSError):
                if os.path.lexists(staging):
                    shred_file(staging)
            raise
        self._discard_retired()
        _fsync_directory(self.directory)

    def _discard_retired(self) -> None:
        """Shred the replaced copy -- unless it is still the live file.

        A write interrupted between the link and the rename leaves the old
        name as a second link to the LIVE document; shredding that would
        destroy the store, so it is only unlinked.
        """
        retired = self.directory / STORE_RETIRED_NAME
        if not os.path.lexists(retired):
            return
        try:
            same = os.path.samestat(os.lstat(retired), os.lstat(self.path))
        except FileNotFoundError:
            same = False
        if same:
            os.unlink(retired)
        else:
            shred_file(retired)

    def create(self, document: dict) -> dict:
        """Make the 0700 directory and write the first document into it."""
        if self.exists():
            raise CustodyError(
                f"a custody store already exists: {self.directory}")
        base = {
            "schema": STORE_SCHEMA, "kind": STORE_KIND, "scope": self.scope,
            "name": self.name, "created_utc": _now(), "note": NOTE,
        }
        if self.scope == SCOPE_INSTANCE:
            base["accounts"] = {}
        else:
            base["break_glass"] = {}
        base.update(document)
        self.directory.mkdir(mode=0o700)
        os.chmod(self.directory, 0o700)
        try:
            with self._locked():
                self._write(base)
        except BaseException:
            with contextlib.suppress(CustodyError, OSError):
                self.shred()
            raise
        return base

    def update(self, mutate: Callable[[dict], None]) -> dict:
        """Read, change and atomically rewrite under the store's lock."""
        with self._locked():
            document = self.read()
            mutate(document)
            self._write(document)
            return document

    def values(self) -> tuple[str, ...]:
        """Every credential the store holds, for a secret scan's needles."""
        document = self.read()
        found: list[str] = []
        for key in ("console", "administrator"):
            if document.get(key):
                found.append(document[key])
        for entry in document.get("accounts", {}).values():
            found += [entry[key] for key in ACCOUNT_SECRET_FIELDS
                      if entry.get(key)]
        for entry in document.get("break_glass", {}).values():
            found += [entry[key] for key in ("current", "pending")
                      if entry.get(key)]
        return tuple(dict.fromkeys(found))

    def shred(self) -> None:
        """Shred every file of the store, then remove its directory.

        Refuses, before touching anything, a directory holding anything but
        the store's own names or a symlink among them.
        """
        if not self.exists():
            return
        self._check_directory()
        entries = list(os.scandir(self.directory))
        unexpected = sorted(
            entry.name for entry in entries
            if entry.name not in STORE_NAMES or entry.is_symlink()
            or not entry.is_file(follow_symlinks=False))
        if unexpected:
            raise CustodyError(
                "refusing: the custody store holds unexpected entries: "
                + ", ".join(unexpected))
        # The live document first, so an interruption leaves no copy of it
        # under its own name; a leftover second link is shredded with it.
        entries.sort(key=lambda entry: entry.name != STORE_NAME)
        for entry in entries:
            if os.path.lexists(entry.path):
                shred_file(Path(entry.path))
        os.rmdir(self.directory)
        _fsync_directory(self.state)


# -- sources ------------------------------------------------------------------
class OwnerCredentialSource:
    """Today's behaviour: the runner's own prompt, with the runner's own text.

    *prompt* is the runner's prompt function (``_typed_secret`` or the one a
    caller passed), called exactly as the runner always called it: with only
    the prompt text, or with ``confirm=`` when a value is typed twice.
    """

    custody = OWNER
    agent = False

    def __init__(self, prompt: Callable[..., bytes]) -> None:
        self._prompt = prompt

    def __repr__(self) -> str:
        return "OwnerCredentialSource()"

    def ask(self, prompt: str, confirm: str | None = None) -> bytes:
        if confirm is None:
            return self._prompt(prompt)
        return self._prompt(prompt, confirm=confirm)

    def console(self, prompt: str) -> bytes:
        return self.ask(prompt)

    def scan_values(self) -> tuple[str, ...]:
        return ()


class AgentCredentialSource:
    """A throwaway instance's own credentials, read from and written to its store.

    Every value handed out is ``bytes`` or ``str`` in memory only; nothing
    here prints, and every refusal names a role or a slot, never a value.
    """

    custody = AGENT
    agent = True

    def __init__(self, store: CustodyStore,
                 workstation_store: CustodyStore | None = None) -> None:
        self.store = store
        self.workstation_store = workstation_store

    def __repr__(self) -> str:
        return f"AgentCredentialSource({self.store.name!r})"

    def scan_values(self) -> tuple[str, ...]:
        values = list(self.store.values())
        if (self.workstation_store is not None
                and self.workstation_store.exists()):
            values += self.workstation_store.values()
        return tuple(dict.fromkeys(values))

    # -- the instance's own ----------------------------------------------
    def console(self, prompt: str | None = None) -> bytes:
        return self.store.read()["console"].encode("utf-8")

    def administrator(self) -> str | None:
        return self.store.read().get("administrator")

    def issue_administrator(
        self, checks: Iterable[Callable[[str], str | None]] = (),
    ) -> str:
        """The domain Administrator password, generated and stored first.

        Stored BEFORE provisioning can take it, so a run that dies after the
        directory accepted it still leaves the value in custody.  An existing
        value is reused, never replaced: provisioning sets it only once.
        """
        existing = self.administrator()
        if existing:
            return existing
        value = generate_password(
            checks=checks, avoid=self.store.values())

        def put(document: dict) -> None:
            if not document.get("administrator"):
                document["administrator"] = value
        document = self.store.update(put)
        return document["administrator"]

    # -- directory accounts, by contract role -------------------------------
    def account(self, role: str) -> dict:
        return dict(self.store.read().get("accounts", {}).get(role) or {})

    def staging_value(
        self, role: str, *, temporary: bool,
        checks: Iterable[Callable[[str], str | None]] = (),
        avoid: Iterable[str] = (),
    ) -> str:
        """The value staging creates *role* with, stored before it is used.

        An existing stored value of the same kind is reused: staging is
        create-only, so a retry either creates the account with it or stops
        on the account that already holds it.
        """
        field = "temporary" if temporary else "current"
        existing = self.account(role).get(field)
        if existing:
            return existing
        value = generate_password(
            checks=checks, avoid=(*self.store.values(), *avoid))

        def put(document: dict) -> None:
            entry = document.setdefault("accounts", {}).setdefault(role, {})
            entry[field] = value
        self.store.update(put)
        return value

    def begin_pending(self, role: str, value: str, *, kind: str,
                      must_change: bool = False) -> None:
        """Record a value about to be set, BEFORE anything can set it."""
        if kind not in (PENDING_FIRST_LOGON, PENDING_RESET):
            raise CustodyError(f"unknown pending kind {kind!r}")

        def put(document: dict) -> None:
            entry = document.setdefault("accounts", {}).setdefault(role, {})
            entry.update(pending=value, pending_kind=kind,
                         pending_must_change=bool(must_change),
                         pending_not_live_utc=None)
        self.store.update(put)

    def promote_pending(self, role: str) -> None:
        """The pending value is proven live: it becomes the account's own.

        A first-logon change or a permanent reset makes it ``current``; a
        reset that must be changed at the next logon makes it ``temporary``.
        """
        def put(document: dict) -> None:
            entry = document.setdefault("accounts", {}).setdefault(role, {})
            value = entry.get("pending")
            if not value:
                raise CustodyError(f"{role} has no pending credential")
            if (entry.get("pending_kind") == PENDING_RESET
                    and entry.get("pending_must_change")):
                entry.update(temporary=value, current=None)
            else:
                entry.update(current=value, temporary=None)
            entry.update(pending=None, pending_kind=None,
                         pending_must_change=None, pending_not_live_utc=None)
        self.store.update(put)

    def mark_pending_not_live(self, role: str) -> None:
        """A login proved the pending value is NOT the account's password."""
        def put(document: dict) -> None:
            entry = document.setdefault("accounts", {}).setdefault(role, {})
            if entry.get("pending"):
                entry["pending_not_live_utc"] = _now()
        self.store.update(put)

    def live_current(self, role: str) -> bytes:
        """The proven, permanent password of *role*, or a refusal."""
        entry = self.account(role)
        if entry.get("pending"):
            raise CustodyError(
                f"{role} has a pending, unproven password change in custody; "
                "finish it first (durable-arch-join proves a first-logon "
                "change, homelab-factory-persistent-account-password a reset)")
        if not entry.get("current"):
            raise CustodyError(
                f"custody holds no proven current password for {role}"
                + ("; its temporary one must be changed at first logon, which "
                   "durable-arch-join does" if entry.get("temporary") else ""))
        return entry["current"].encode("utf-8")

    # -- the kept workstation's break-glass passwords ------------------------
    def _workstation(self) -> CustodyStore:
        if self.workstation_store is None:
            raise CustodyError("this run has no kept workstation custody")
        return self.workstation_store

    def begin_break_glass(
        self, slot: str, *, checks: Iterable[Callable[[str], str | None]] = (),
        avoid: Iterable[str | bytes] = (),
    ) -> str:
        """A new break-glass password, stored as pending before any boot."""
        if slot not in BREAK_GLASS_SLOTS:
            raise CustodyError(f"unknown break-glass slot {slot!r}")
        store = self._workstation()
        if not store.exists():
            store.create({})
        value = generate_password(
            checks=checks,
            avoid=(*self.store.values(), *store.values(), *avoid))

        def put(document: dict) -> None:
            entry = document.setdefault("break_glass", {}).setdefault(slot, {})
            entry["pending"] = value
        store.update(put)
        return value

    def promote_break_glass(self, slot: str) -> None:
        """The workstation folded the stage that set it: pending is current."""
        def put(document: dict) -> None:
            entry = document.setdefault("break_glass", {}).setdefault(slot, {})
            if not entry.get("pending"):
                raise CustodyError(f"{slot} has no pending credential")
            entry.update(current=entry["pending"], pending=None)
        self._workstation().update(put)


def instance_store(target: object) -> CustodyStore:
    """The custody store of a persistent instance (``PersistentControllerInstance``)."""
    return CustodyStore(
        Path(getattr(target, "state")), scope=SCOPE_INSTANCE,
        name=str(getattr(target, "instance")))


def workstation_store(state: Path, name: str) -> CustodyStore:
    return CustodyStore(Path(state), scope=SCOPE_WORKSTATION, name=name)


def instance_custody(target: object) -> str:
    """An instance's custody from its marker; no marker yet means the owner's."""
    exists = getattr(target, "exists", None)
    if callable(exists) and not exists():
        return OWNER
    return marker_custody(target.read_marker())


def credential_source(
    target: object, *, prompt: Callable[..., bytes],
    workstation: tuple[Path, str] | None = None,
) -> OwnerCredentialSource | AgentCredentialSource:
    """The source a runner uses for *target*, chosen from its marker.

    *workstation* is ``(state, name)`` of the kept workstation a stage runs
    on, which inherits the instance's custody.  Refused: a custody store
    beside an owner-custody instance or workstation (owner custody never
    stores a credential), and an agent-custody instance whose store is gone
    (its console credential with it).
    """
    custody = instance_custody(target)
    state = Path(getattr(target, "state"))
    if custody == OWNER:
        if os.path.lexists(state / CUSTODY_DIR_NAME):
            raise CustodyError(
                f"the owner-custody instance {getattr(target, 'instance')} "
                "holds a custody store; owner custody never stores a "
                "credential, so this refuses rather than read it")
        if workstation is not None and os.path.lexists(
                Path(workstation[0]) / CUSTODY_DIR_NAME):
            raise CustodyError(
                f"the kept workstation {workstation[1]} holds a custody store "
                "but its instance is owner custody; refusing")
        return OwnerCredentialSource(prompt)
    store = instance_store(target)
    if not store.exists():
        raise CustodyError(
            f"the agent-custody instance {store.name} has lost its custody "
            "store, and with it the only copy of its console credential; "
            "destroy and recreate the throwaway instance")
    store.read()
    wstore = None
    if workstation is not None:
        wstore = workstation_store(Path(workstation[0]), workstation[1])
        if wstore.exists():
            wstore.read()
    return AgentCredentialSource(store, wstore)


def custody_scan_values(target: object) -> tuple[str, ...]:
    """Every stored value of an agent-custody instance; nothing for the owner's.

    For a transcript scan that must fail closed: an agent-custody instance
    whose store cannot be read raises ``CustodyError``.
    """
    if instance_custody(target) != AGENT:
        return ()
    return instance_store(target).values()
